#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# (c) Copyright 2020 - 2022 Xilinx, Inc. All rights reserved.

[ -e "./scripts/guess.sh" ] && source "./scripts/guess.sh"

. $TE_BASE/scripts/guess.sh
te_trc_update_wrapper --def-conf-tester=./conf/tester.conf \
    --def-db=trc/top.xml "$@"
